### ISSUE TITLE
'extensible' bindings: override binding or use ConceptMap?

### ISSUE THREAD

**Issue by jduwel** [Nictiz/Nictiz-R4-zib2020#102]
Encounter.class in zib-Encounter (#49 ) has an extensible binding.

At the moment, a ConceptMap (ContactTypeCodeLijst-to-ActEncounterCode) is created to map the zib ValueSet to the fhir ValueSet. All equivalences are 'equal', so I think this is a nice approach. However, one could also argue to override the binding to our own zib ValueSet.

The Profiling Guidelines do not offer guidance on how to deal with extensible bindings. Any thougts?

**Comment by jduwel** [comment]
The situation in Encounter.class turns out to be a bit different: there is one value (UNK) that is not present in the fhir ValueSet, leading to one concept that has equivalence 'unmatched' (this error also seems present in STU3). This is allowed because the binding is 'extensible'. All other concepts are actually from the same CodeSystem (zib ValueSet is a subset of fhir ValueSet).

However, I think the issue is still relevant because of other possible 'extensible' bindings.

**Comment by pieter-edelman-nictiz** [comment]
When there's an extensible binding, you are allowed to use additional codes as long as they don't represent the same concept as is found in the base binding. If the concept is found in the base ValueSet, the code from this ValueSet must be used.

**Comment by jduwel** [comment]
True. Shouldn't we state explicitly in the guidelines that a ConceptMap should always be created in these cases?

**Comment by ArdonToonstra** [comment]
I think we can indeed explicitly add in the profiling guidelines that a ConceptMap should be created and added if the codes in a zib valueset can be mapped to an extensible valueset in FHIR.

**Comment by jduwel** [comment]
Turns out I was mixing the definitions of 'perferred' and 'extensible' bindings when creating this issue, so it will be closed.

A possible situation where this discussion might be relevant again is if we would like to map a zib ValueSet to an extensible FHIR ValueSet, with 'a few' zib concepts matching FHIR and 'a few' new/extra zib concepts. Would the most correct strategy be to create a new "hybrid" ValueSet? Is a ConceptMap needed? However, this situation probably hasn't occurred (yet), issue can be reopened if it does.
