### ISSUE TITLE
DispenseRequest - how to map 'FinancieleIndicatiecode'

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#106]
How to map [FinancieleIndicatiecode ](https://decor.nictiz.nl/art-decor/decor-datasets--mp-?id=2.16.840.1.113883.2.4.3.11.60.20.77.1.4&effectiveDate=2021-01-01T00%3A00%3A00&conceptId=2.16.840.1.113883.2.4.3.11.60.20.77.2.4.592&conceptEffectiveDate=2021-03-23T09%3A35%3A02&language=nl-NL) into the nl-core-DispenseRequest profile. Seems like this would become an extension. What would be the English name for it?

**Comment by weteringac** [comment]
In de dataset noemen we het 'financial indication code'

In SNOMED is de eng vertaling: "Indication for reimbursement of medication (observable entity)"

**Comment by ArdonToonstra** [comment]
Created an extension for it and added it to the nl-core-profile. I wonder what to do with the guidance on usage of codes for this field.  I tried to provide some English guidance in the `comment`, but I wonder if the functional definition isn't lacking a ValueSet of some sort.

**Comment by weteringac** [comment]
Yes, IA's are working on valueset (or at least a limited set of codeSystems from which to use values, because it is an externally maintained list), see https://bits.nictiz.nl/browse/MP-44, they asked for oid for codeSystem

**Comment by ArdonToonstra** [comment]
Ok! I hope what we have will suffice then. Will close this issue for now.
