### ISSUE TITLE
VerpleegkundigeInterventie: Procedure of CarePlan?

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#108]
De zib VerpleegkundigeInterventie is in STU3 primair geïmplementeerd als profiel op de FHIR-resource Procedure (alhoewel er een tweede implementatie is voor de BgLZ op CarePlan). Bij het maken van de R4-implementatie komt de vraag naar boven of CarePlan niet een betere resource is voor deze zib.

De redenatie hierachter is dat een Procedure een enkele concrete ingreep (al dan niet in de toekomst) vertegenwoordigt, op een vastgesteld tijdstip. Alhoewel de zib er geen eenduidige omschrijving over doet, komt uit de beschrijving, de voorbeelden en het gebruik binnen informatiestandaarden komt het beeld naar voren dat eerder een _plan_ is dan een _concrete actie_, met mogelijke herhalingen (moet twee keer per week uitgevoerd worden) en conditionaliteiten (patiënt ondersteunen wanneer deze hoest). Dit past conceptueel goed bij een CarePlan en minder bij een Procedure.

Dit blijkt ook uit de mapping van de zib naar de FHIR-resource: Procedure bevat geen concepten voor behandeldoel (alleen vastgestelde uitkomst) of herhalingen (alleen datum/tijd van uitvoer). Deze concepten moeten via extensies worden toegevoegd. CarePlan biedt wel ondersteuning voor deze concepten, alhoewel er weer geen concept is voor te gebruiken MedischHulpmiddel waarvoor alsnog een extensie gemaakt zou moeten worden (m.i. is dat minder fundamenteel dan de extensies op Procedure).

Overigens is er nog een derde optie: ServiceRequest. Conceptueel komt deze ook overeen, maar de mapping is minder goed, o.m. door het ontbreken van een concept voor doel.

**Comment by pieter-edelman-nictiz** [comment]
Nog een toevoeging: in de 2017-versie van de zib VerpleegkundigeInterventie waren er meerdere VerpleegkundigeActie's per VerpleegkundigeInterventie mogelijk, maar [op verzoek van V&VN](https://bits.nictiz.nl/browse/ZIB-728) is dit onderscheid geschrapt. Gemapt op CarePlan zou een VerpleegkundigeInterventie dus een CarePlan met slechts een enkele '.activity` worden.

**Comment by pieter-edelman-nictiz** [comment]
Jacob Engel: In de zib documentatie: "Een verpleegkundige interventie wordt vastgelegd om het verpleegkundig beleid te documenteren en om andere zorgverleners daarvan op de hoogte te stellen." De concepten Frequentie en Interval duiden daar ook op. In de BgLZ en in de eOverdracht maken ze deel uit van de sectie Zorgplan.
    
Dit in tegenstelling tot de zib verrichting: "Het concept Verrichting beschrijft een therapeutische of diagnostische verrichting, die de patiënt heeft ondergaan of zal ondergaan."

**Comment by ArdonToonstra** [comment]
Na enige onderzoek kom ik ook tot de conclusie dat CarePlan een betere match is. Met name de concepten Frequentie en Interval geven m.i. weg dat het om iets anders gaat dan een feitelijke verrichting.

**Comment by ArdonToonstra** [comment]
Superseded by #197
