### ISSUE TITLE
zib-MedicationDispense status; indirect mapping possible

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#122]
`MedicationDispense.status` is required by FHIR, but has no direct functional relationship to the zib. Would it be possible to map this indirectly based on RequestDate and MedicationDispenseDateTime, eg:

|                                                                    | RequestDate in the past    | RequestDate in the future |
--- | --- | ---
| MedicationDispenseDateTime in the past    | _completed_                      | -                                       |
| MedicationDispenseDateTime in the future | _preparation_                    | _preparation_                    |

**Comment by ArdonToonstra** [comment]
I believe we can make an indirect mapping for MedicationDispenseDateTime present and in the past to _completed_. However, I think MedicationDispenseDateTime and RequestDate will always be a current date or in the past. I don't think these concepts are meant for future dates. Need to check.

**Comment by weteringac** [comment]
In MP information standard we only communicate actual "medicatieverstrekkingen", so for zib medicationDispense, this is not so much an issue, it is always completed.

However, you will run into the same problem with "toedieningsafspraak" which is also in FHIR resource MedicationDispense, this is more of a challenge. Raise separate issue?

**Comment by ArdonToonstra** [comment]
That's what I thought too. I added a bit more documentation in the zib-MedicationDispense profile and included the changes in the mappings. I will close this issue. Please reopen it Pieter, if you think it is not sufficient. 

I will open a separate issue for the zib-AdministrationAgreement.
