### ISSUE TITLE
How should we distinguish DesiredHealthcareResult and DesiredHealthCondition::FunctionalOrMentalStatus?

### ISSUE THREAD

**Issue by Ashwin-nictiz** [Nictiz/Nictiz-R4-zib2020#125]
Following Pieter's answer in issue number [#111 ](https://github.com/Nictiz/Nictiz-R4-zib2020/issues/111) it's a great idea to modulate FunctionalOrMentalStatus directly in the profile instead of a reference. Below is a quote from the issue:

_However, the Goal resource offers the necessary parts to represent a FunctionalOrMentalStatus in the future. Therefore it seems like a better approach to model FunctionalOrMentalStatus directly as part of this profile._

Each element gets its own slice and a code to distinguish. Unfortunately there is no definition code available for the element DesiredHealthCondition::FunctionalOrMentalStatus. How can we clarify for this concept anyway?

Potential solutions:

1. We ask the zib center for a definition code
2. Accompanying text in the comment section

**Comment by Ashwin-nictiz** [comment]
In the Goal resource, the element description is a mandatory element. This makes it impossible to add a constraint, because desccription must always be filled.

**Comment by ArdonToonstra** [comment]
Potential solution number 1 is a dead end: https://bits.nictiz.nl/browse/ZIB-1549

**Comment by ArdonToonstra** [comment]
Would it be possible to deduce that `Goal.description` is a DesiredHealthCondition when `Goal.target` and/or `Goal.addresses`  is present?

**Comment by Ashwin-nictiz** [comment]
I think `Goal.target` only is enough to deduce `Goal.description`, but there must be a piece of explanation written down that `Goal.target` is linked with `Goal.description`

**Comment by Ashwin-nictiz** [comment]
In consultation we have decided that it is not important that the recipient can't make a distinction. The current situation meets the requirements.

**Comment by ArdonToonstra** [comment]
To add to Ashwin comments: that means that if a DesiredHealthcareResult is given in the Goal resource, the `Goal.description` get the value of a concatenated value derived from the DesiredHealthcareResult which may be received as a DesiredHealthCondition for the recipient. We don't think that will be a big problem.
