### ISSUE TITLE
Is the FHIR CodeableConcept datatype a proper implementation of Coded Ordinal?

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#140]
https://zibs.nl/wiki/FunctionalOrMentalStatus-v3.2(2020EN) has a Coded Ordinal for the concept StatusValue. This is currently mapped to `Observation.valueCodeableConcept`. Does this suffice? Does it require additional constraints?

If we agree this is can be mapped, we should improve the profiling guidelines and tooling. One of the errors:

>     == NL-CM:4.26.3 (Observation.value[x]:valueCodeableConcept)
>       datatype:    ERROR (CodeableConcept instead of CO)

**Comment by pieter-edelman-nictiz** [comment]
Coded Ordinal is a specialization of Coded Description, and FHIR doesn't have a specific datatype for this specialization than CodeableConcept -- it's more a property of the ValueSet than the actual datatype IMO. The profiling guidelines already state that it is a proper mapping, so I'll update the tooling.

We _could_ define a datatype profile that does nothing else than include a default comment that the values can be used for calculation, but I think this is a bit overkill, as comments are not guaranteed to be overridden, and like I said, it's actually more a property of the ValueSet.

**Comment by pieter-edelman-nictiz** [comment]
This is fixed in the tooling and as far as I can see in both branches mentioned. I'm closing this issue.
