### ISSUE TITLE
How to accommodate the concept section of a zib when it's a datatype profile

### ISSUE THREAD

**Issue by LuudSlagter** [Nictiz/Nictiz-R4-zib2020#177]
The Concept description that is present in the zibs is automatically mapped to `StructureDefinition.description`. However, when a zib is implemented as a datatype profile, this description is never shown. An example is the zib MaritalStatus, which is part of the zib-Patient profile. What is the best way to handle these descriptions?

Proposal:
- If the Concept description does not offer any meaningful additions to the definition of the concept that is mapped to in the FHIR profile, nothing needs to be done. 
Example: the zib Nationality has Concept 'Nationality is used as an indication of the country of citizenship.' and definition 'Indicates the country of citizenship.', so no meaningful addition.
- If the Concept description can be seen as an extension of the definition of the concept that is mapped to in the FHIR profile, the description should be changed manually. 
Example: the zib MaritalStatus has Concept 'Marital status is a person’s formal position as defined by the Dutch civil code. There is a distinction between marriage and civil union.' and definition 'A person’s marital status according to the terms and definition in the Dutch civil code.'. Here the second sentence in the Concept can be seen as a valuable addition.

**Comment by ArdonToonstra** [comment]
Luud will make a PR for the zib Patient profile.

**Comment by pieter-edelman-nictiz** [comment]
@ArdonToonstra @LuudSlagter could you describe the outcome of the discussion here?

**Comment by LuudSlagter** [comment]
For zibs that are implemented as a datatype profile we put the text that is in the 'Concept' section of the zib in the `.description` element of the 'parent' zib profile. (In the mentioned example this means that the 'Concept' texts of Nationality, MaritalStatus and LanguageProficiency should be included in the `.description` of the Patient profile. Apparently this was already the case for the first two, so only LanguageProficiency still needs to be included there. See https://github.com/Nictiz/Nictiz-R4-zib2020/pull/203.)

**Comment by ArdonToonstra** [comment]
I believe we can safely close this issue as #203 is merged.
