### ISSUE TITLE
Ada2FHIR issues zib NutritionAdvice

### ISSUE THREAD

**Issue by LuudSlagter** [Nictiz/Nictiz-R4-zib2020#179]
Currently there are two issues that make it difficult to properly convert a zib/ada instance to a FHIR instance:

- Based on the type of food the concept Consistency is mapped to either `.oralDiet.texture.modifier.text` (solid food) or `.oralDiet.fluidConsistencyType.text` (fluids). There is however no indicator for the type of food present in the zib, making it impossible to determine to which element the Consistency should be mapped. For now it seems best to use `.oralDiet.texture.modifier.text` in the Ada2FHIR mapping in all cases.
- The NutritionOrder resource contains a mandatory element `.dateTime`; however no equivalent is present in the zib. For now the current date/time is used in the Ada2FHIR mapping to populate this element.

**Comment by ArdonToonstra** [comment]
The first bullet poses quite a problem. Perhaps this kind of information is known in the health process? This is definitely something to discuss with the zib-centre/
The second bullet should perhaps not be a real problem for implementers. Tracking DateTimes would be pretty common.

**Comment by LuudSlagter** [comment]
I've created a zib ticket, see https://bits.nictiz.nl/browse/ZIB-1617.

**Comment by LuudSlagter** [comment]
Currently the zib doesn't provide enough information to determine the right mapping of consistency. Hence, based on ZIB-1617, we map the consistency to `.oralDiet.fluidConsistencyType.text` in Ada2FHIR (for now), and moreover add a warning message to the stylesheet indicating this issue.

**Comment by pieter-edelman-nictiz** [comment]
@LuudSlagter , I think this issue can be closed now, correct?

**Comment by LuudSlagter** [comment]
In the meantime, the default mapping has been changed to `.oralDiet.texture.modifier.text`, and the warning has been updated accordingly. Since there is no satisfying answer given in ZIB-1617, we can close this issue!
