### ISSUE TITLE
TextResult.SOAPLine.SOAPLineCode mapping

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#181]
The [SOAPLineCode (NL-CM:13.6.5)](https://zibs.nl/wiki/SOAPReport-v1.0(2020EN)) concept allows communicating a code for an S or E SOAPLine. 

The SOAPLine is mapped to an Observation with the SOAPLineHeader on `Observation.code` and the SOAPLineText on `Observation.valueString`. 

It is not completely clear how we could best map **SOAPLineCode**. There are at least the following three options:

1. In STU3 this has been modelled in a `Observation.component`. We do not have a proper code for the `Observation.component.code` (https://bits.nictiz.nl/browse/ZIB-1448) that clearly identifies the component. 
2. Use an extension that defines the SOAPLineCode. This can be added to the root of the Observation, or more specifically, to `Observation.valueString`, as this code actually states something about the value of the Observation.
3. We could use `Observation.valueCodeableConcept` for both concepts: `Observation.valueCodeableConcept.text` for SOAPLineText and Observation.valueCodeableConcept.coding` for SOAPLineCode. This omits the use of another extension. It does however feels a bit odd. Normally you use a CodeableConcept for coded elements where you can use an unstructured free text to describe the concept. In this scenario, we would then firstly use the unstructured text option that may have a code that represents the most important part of the text.

**Comment by ArdonToonstra** [comment]
Ping @ahenket  :)

**Comment by pieter-edelman-nictiz** [comment]
@LuudSlagter , @niekvangalen , aangezien jullie bezig zijn met SOEPVerslag ...
