### ISSUE TITLE
Documenting reversed references

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#186]
Occasionally, FHIR will define references in the opposite direction of what the zib requires, e.g. zib TextResult defines a reference to a zib Procedure instance, but in FHIR this is best implemented using the `Procedure.report` element, so the reference points the other way around.

Using the normal mapping mechanism with the corresponding metadata on this reversed reference leads to strange references, e.g. the `.short` for `Procedure.report` would be "Procedure".

Proposal for a better mechanism in these scenarios:
* On the element that represents the reference:
  * `mapping` contains the mapping of the reference that's being mapped, but `.mapping.comment` will be "Reversed reference for zib [zib name].[concept name]" (e.g. "Reversed reference for zib TextResult.Procedure")
  * `short` and `alias` contains the English and Dutch names of the zib that's being referenced
  * `comment` contains an additional note in the form of "Please note that zib [xxx] references zib [xxx], but in FHIR this direction is reversed."

**Comment by pieter-edelman-nictiz** [comment]
Proposal: https://informatiestandaarden.nictiz.nl/wiki/FHIR:Vissue-GitHub-186_FHIR_Profiling_Guidelines_R4#References_that_are_reversed_in_FHIR

**Comment by ArdonToonstra** [comment]
Looks good!:
Summary of discussed points:

- No guidance about slicing here (not every reference can be sliced due to 0..1)
- Mention that is allowed to leave out the definition mapping. It can be populated based on author's best insights?
- Mention that the reference profile should contain a note on the root comment that the reference is reversed.

**Comment by pieter-edelman-nictiz** [comment]
Guidance integrated to Vprepub, the zib compliance tool has been adjusted.
