### ISSUE TITLE
zib compliance QA tooling: improve conceptually cardinality check

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#187]
The zib has declared its cardinalities as conceptual: https://zibs.nl/wiki/Zib_kardinaliteiten. The QA tooling keeps this into account. It does so however by subtracting 1 on the min cardinality. In zib-MultidisciplinaryTeamMeeting, the concept Participant (NL-CM:15.2.13) has a conceptual cardinality of 2..* which should be translated in the profile to 0..* . The QA tooling now incorrectly expects 1..* .   

An improvement for the zib documentation would be to also highlight this example (having a min higher than 1) to the documentation...

**Comment by pieter-edelman-nictiz** [comment]
This is fixed, closing this topic.
