### ISSUE TITLE
Profiling/mapping MedicalDevice (ProductID)

### ISSUE THREAD

**Issue by LuudSlagter** [Nictiz/Nictiz-R4-zib2020#188]
The zib MedicalDevice contains the concept ProductID, which leads to a lot of confusion. In https://bits.nictiz.nl/browse/ZIB-1535 (some of) the underlying issues are already discussed. The following topics still require some follow-up discussion:

1. 
Based on the discussion in ZIB-1535 there is no fixed format for ProductID (it could be either a UDI or something else; the zib however is not very clear in that regard); apparently uniqueness is more important than the exact structure of the ProductID. The element `Device.identifier:productID` in the profile zib-MedicalDevice.Product however contains the pattern `<system value="http://terminology.hl7.org/CodeSystem/v2-0203" /> <code value="SNO" />` which is only applicable for serial numbers (note that this is mentioned as an example in the definition of ProductID in the zib), and moreover the definition in the profile is completely focused on serial numbers. **We should probably remove this pattern and change the definition, as these are too strict/narrow.**

2. 
In the profile zib-MedicalDevice.Product the concept ProductID is mapped explicitly to `.identifier:productID`, and implicitly to `.udiCarrier.deviceIdentifier`, `.udiCarrier.issuer`, `.udiCarrier.carrierHRF`, `.manufactureDate`, `.expirationDate`, `.lotNumber` and `.serialNumber`. 
Regardless of the used coding system to identify the device, it seems that `.identifier:productID` and `.udiCarrier.carrierHRF` should contain the full ProductID. Moreover `.udiCarrier.issuer` can easily be determined based on the used code system (at least for GS1 and HIBC). For the other attributes (let's refer to these as **secondary**) the following holds true:

   * If GS1 is used the mapping is quite easy (see https://www.gs1.nl/en/gs1-standards-industries/unique-identification-and-product-data-healthcare/gs1-barcodes-healthcare-1):
     * `.udiCarrier.deviceIdentifier` (i.e. the 'DI') is actually the GTIN, i.e. the code after '(01)';
     * `.manufactureDate` is the code after '(11)' - the only difficulty lies in the format 'YYMMDD';
     * `.expirationDate` is the code after '(17)' - the only difficulty lies in the format 'YYMMDD';
     * `.lotNumber` is the code after '(10)';
     * `.serialNumber` is the code after '(21)'.
   * If HIBC is used the mapping is quite complicated (see https://www.barcodefaq.com/udi/hibc/ or the file attached to ZIB-1535):
     * `.udiCarrier.deviceIdentifier` (i.e. the 'DI') is the primary code in HIBC, i.e. the part before the first '/'.
     * The other four elements can be derived as well, but the logic involved is much more complicated than for GS1.
   * If another system is used we are not able to determine the values of the mentioned elements in FHIR. Moreover, based on the current definition of the zib, it's not even possible to use other systems (so we probably shouldn't spend too much time on these systems).

Thus we need to decide on the following:
- **Do we add specific mappings in FHIR for the secondary attributes?** If not, we should remove the mapping to NL-CM:10.1.4 in the profile for these attributes. In any case I think we should at least add guidance/links to documentation w.r.t. the usage of GS1 and HIBC, so that it's easier to implement this zib.
- **If we decide to (partly) support these specific mappings, in what detail do we construct the ada-to-FHIR mapping?** It seems unsatisfactory to not include all mappings for GS1, as these are straightforward and not prone to further interpretation. For HIBC we should also be able to fully incorporate these mappings, but the logic is more difficult and prone to error (and additional consultation with the zib centre might be necessary). However, if we add the explicit mappings for GS1 and/or HIBC, we should probably add a disclaimer to the ada-to-FHIR mapping itself, since the logic therein will be based on receiving a full UDI as ProductID and might lead to an incorrect result if only part of the UDI is received instead (especially in the case of HIBC).

**Comment by ArdonToonstra** [comment]
Regarding 1: as discussed there is also the UDI code but that will be too narrow as well. Without the use of a `identifier.type` it will be very hard to differentiate between the `identifier` slices: it will not be possible to be certain which `identifier` holds the ProductID information. 
We could remove the mapping on `.identifier` because ProductID is also mapped to `.udiCarrier.carrierHRF`. Perhaps we will only introduce more confusion if we specify how to use the `.identifier` with regards to ProdcutID on top of FHIR. 

Regarding 2: `.udiCarrier.issuer` and `.udiCarrier.carrierHRF` should both get a direct mapping.
Mm, I am not sure what the best course of action is. We already have spent a lot of time and effort researching how to map GS1 and HIBC to structured fields in FHIR. It feels like a waste if we let implementers go through the same effort. So I do agree with your 'in any case we should add documentation'. On the other hand, the zib (nor information standards) don't require it. So perhaps we are adding more complexity and more chance of errors than necessary.

**Comment by ArdonToonstra** [comment]
Meeting conclusion:
- Use `Device.identifier` as main mapping for ProductID, remove the pattern with _SNO_ as `Identifier.type`. Discriminate slice based on ValueSet binding on `.identifier.system` 
- Add a clear comment that `.udiCarrier.issuer`, `.udiCarrier.carrierHRF` that these can only be used if ProcuctID is a UDI and model this on two slices with at fixed value on `.udiCarrier.issuer`
- Remove (implicit) mapping from   `.manufactureDate`, `.expirationDate`, `.lotNumber` and `.serialNumber` and replace with comments if they are useful for the implementer (after all our hard labour regarding researching this)

- Create/comment another time in zib ticket to make clear that the zib does not provide enough functional support.

**Comment by pieter-edelman-nictiz** [comment]
I believe all conclusions have been added to the profile, so I'm closing this issue.
