### ISSUE TITLE
NL core Administration Agreement does not yet refer to nl-core-Patient.

### ISSUE THREAD

**Issue by weteringac** [Nictiz/Nictiz-R4-zib2020#207]
NL core Administration Agreement does not yet refer to nl-core-Patient.

https://github.com/Nictiz/Nictiz-R4-zib2020/blob/MedicationProfiles/resources/nl-core/nl-core-AdministrationAgreement.xml

**Comment by jduwel** [comment]
Duplicate(?, actually 'specialization') of #183

**Comment by ArdonToonstra** [comment]
Fixed.
