### ISSUE TITLE
Patterns vs. fixed values

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#211]
FHIR offers two ways to enforce values being present on certain elements: patterns and fixed codes. Until now, we have defined that patterns are the preferred way for CodeableConcept elements because this offers a _minimal_ requirement, allowing for other codes to be present. For other situations, a fixed value is maybe more informative to the implementer.

The proposal is now to add to the profiling guidelines the guidance that patterns are preferred for complex elements while fixed codes are preferred for atomic elements.

**Comment by ArdonToonstra** [comment]
To use the FHIR terminology (https://www.hl7.org/fhir/datatypes.html):
* Primitive Types = fixed
* General-purpose complex types = pattern

**Comment by pieter-edelman-nictiz** [comment]
Will be solved via https://bits.nictiz.nl/browse/MM-4968. Closing this issue.
