### ISSUE TITLE
zib Procedure: reference to zib MedicalDevice

### ISSUE THREAD

**Issue by jduwel** [Nictiz/Nictiz-R4-zib2020#217]
Earlier, zib Procedure referenced zib MedicalDevice by referencing the DeviceUseStatement resource (the 'main' profile of MedicalDevice) in `focalDevice.manipulated`. Conceptually, this seems a perfect fit, but `focalDevice.manipulated` can only reference the Device resource part of MedicalDevice.

I can see two possible solutions:
- Reference DeviceUseStatement either by some extension or reverse the reference through `DeviceUseStatement.derivedFrom`.
- Reference Device in `focalDevice.manipulated` and account for the 'missing concepts'.

The first solution might be the easiest FHIR-wise, but conceptually the second matches better. The definition of `focalDevice.manipulated` matches the intent of the reference between the zibs, while the definition of DeviceUseStatement speaks of "This also is distinct from the Procedure resource which may describe the implantation or explantation of a device.". When looking at zib Procedure and zib MedicalDevice, it looks like all concepts present in the DeviceUseStatement part of zib MedicalDevice are either already present in zib Procedure or available in the Procedure resource, leading to my belief that it is possible to map these concepts in Procedure as well (thus leading to a MedicalDevice mapping in the zib-Procedure profile).

**Comment by pieter-edelman-nictiz** [comment]
I agree with the last part of your observation. The Resource Device represents the device itself while DeviceUseStatment provides the context about its use. But the context is already given in this situation.

**Comment by ArdonToonstra** [comment]
The definition of Procedure.MedicalDevice talks about 'the product' likely representing the MedicalDevice.Product container. Which lines up with your second solution. Would the zib-centre confirm this assumption? If so, we could go for the second solution and potentially ask for an enhancement of the zib to show this better as well.

**Comment by jduwel** [comment]
https://bits.nictiz.nl/browse/ZIB-1442

**Comment by jduwel** [comment]
Conclusion from zib-ticket: both DeviceUseStatement and Procedure provide context and at first glance it seems that there are matching contexts, but there could be subtle differences. So for the Procedure-event profile, I am implementing solution 1.

For the Procedure-request profile, DeviceUseStatement is referenced in `.supportingInfo`. It could be more consistent so also reverse this reference on `DeviceUseStatement.derivedFrom` for consistency.

**Comment by pieter-edelman-nictiz** [comment]
Change has been merged
