### ISSUE TITLE
medicationuse and medicationadministration both have 'agreed indicator' can we use same extension?

### ISSUE THREAD

**Issue by weteringac** [Nictiz/Nictiz-R4-zib2020#219]
medicationuse and medicationadministration both have 'agreed indicator' can we use same extension?

note: initially the 'agreed indicator' in medicationadministration was named 'deviating administration' but since that really meant the same thing but with a reversed boolean, it has been decided to create unity over these two building blocks.

note: the current extension has a specific name for medicationUse, which should be generalised if this change request is accepted.

**Comment by jduwel** [comment]
https://bits.nictiz.nl/browse/ZIB-1724

**Comment by LuudSlagter** [comment]
Same extension is used in mp-profiles.
