### ISSUE TITLE
toedieningssnelheid (rate) and Gstd quantity

### ISSUE THREAD

**Issue by weteringac** [Nictiz/Nictiz-R4-zib2020#220]
toedieningssnelheid (rate) and Gstd quantity. Gstd quantity cannot be used for rate, because the unit is in fact a ratio (ml/h). This cannot be expressed in Gstd units in one field (unless we make it a ratio with two fields, also in FHIR, which I believe is over the top / not necessary for rate). So it is now confusing the FHIR profile indicates Gstd quantity for fields in which is impossible to use Gstd units.

profile InstructionsForUse and medicationadministration

**Comment by ArdonToonstra** [comment]
Fixed by a commit in #218 for MedicationAdministration and this one #220.
