### ISSUE TITLE
Mapping latest insights

### ISSUE THREAD

**Issue by jduwel** [Nictiz/Nictiz-R4-zib2020#222]
1. Mappings in extensions

Mapping in extensions are not (and will not be) rendered in Simplifier because the contents of the extension are not included in snapshots.

If you duplicate the mapping in a profile, Forge will remove it.

Will we place the mappings in the host profile?
Will we move the mapping to the root of the extension (so they are included in the snapshot)?
Leave everything as is and add some documentation somewhere.

2. Add zib declarations to nl-core profiles
To render the zib mappings in Simplifier view of nl-core profiles.

**Comment by ArdonToonstra** [comment]
For starters, point 2 would be a quick improvement. Not a lot of work, lots of benefits. Wrong design choice in the beginning of removing them all... :( 

Regarding point 1, that may have some more discussion probably. But I would take matters into our own hands by placing the mappings in the host profile just like the STU3 profiles.

**Comment by pieter-edelman-nictiz** [comment]
Relevant ticket: https://firely.atlassian.net/servicedesk/customer/portal/1/SD-767

**Comment by pieter-edelman-nictiz** [comment]
This ticket has been superseded by others, closing.
