### ISSUE TITLE
How to handle not compatible changes with the zib in nl-core?

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#223]
The zibs are slow and information standards may have/require updates earlier than the next release of the zibs. How to handle required changes that are not necessarily compatible with the zib? We should have a strategy for this in place. The following issues can be identified that relate to this:

* Terminology updates to bound valuesets: https://bits.nictiz.nl/browse/MP-445
* Semantic code update - #221 
* Changing a concept's definition and name for harmonization- #219

**Comment by LuudSlagter** [comment]
Closed, since these incompatible changes will be resolved by publishing zib errata (and implemented via the MedicationProfiles-errata branch).
