### ISSUE TITLE
Conceptmap NummerSoortCodeLijst - EmailaddressesUse

### ISSUE THREAD

**Issue by niekvangalen** [Nictiz/Nictiz-R4-zib2020#231]
Copied from [this Zulip-thread](https://chat.fhir.org/#narrow/stream/179181-netherlands/topic/Conceptmap.20NummerSoortCodeLijst.20-.20EmailaddressesUse/near/269584050)

> Hi, on the 2020 Nictiz profile https://simplifier.net/nictiz-r4-zib2020/nlcorecontactinformationemailaddresses one use, I see that there is a ConceptMap https://simplifier.net/nictiz-r4-zib2020/nummersoortcodelijst-to-contactinformation-emailaddressesuse. I am wondering why this NummerSoortCodelijst and not EmailSoortCodelijst, and if this is correct? In the mapping is also referred to EmailSoortCodelijst.

**Comment by pieter-edelman-nictiz** [comment]
Addressed via https://bits.nictiz.nl/browse/MM-4986, closing this issue.
