### ISSUE TITLE
Binding.description guidelines 

### ISSUE THREAD

**Issue by Ashwin-nictiz** [Nictiz/Nictiz-R4-zib2020#295]
As a team we have agreed that we will not fill in the description of Binding.description. In our examples this is filled in with the name of the ValueSet. If no description is entered, the default value of the profile is shown in simplifier.

Examples: https://informatiestandaarden.nictiz.nl/wiki/FHIR:V1.0_FHIR_Profiling_Guidelines_R4_examples 

Do we need to develop guidelines for this?

**Comment by pieter-edelman-nictiz** [comment]
Aanpassingen gedaan op https://informatiestandaarden.nictiz.nl/wiki/FHIR:Vissue-295_FHIR_Profiling_Guidelines_R4_examples en https://informatiestandaarden.nictiz.nl/wiki/FHIR:Vissue-295_FHIR_Profiling_Guidelines_R4#Metadata

**Comment by pieter-edelman-nictiz** [comment]
@Ashwin-nictiz , kan jij de aanpassingen reviewen?

**Comment by Ashwin-nictiz** [comment]
Hallo Pieter,

Akkoord!
