### ISSUE TITLE
Slicing value[x] en effective[x]

### ISSUE THREAD

**Issue by LilianMinne** [Nictiz/Nictiz-R4-zib2020#298]
In het kader van open modeling is een afspraak gemaakt om de polymorfische elementen value[x] en effective[x] te slicen en het data type constraint enkel op de slice toe te passen. De max cardinaliteit van deze elementen is echter 1, waardoor nut en noodzaak voor het slicen in twijfel getrokken kan worden. Aan de andere kant, kan dit wel nuttig zijn in generieke profielen waar meerdere data types zijn toegestaan om mappings per data type te kunnen definieren. 

Het slicen van polymorfische elementen staat wel genoemd in de richtlijnen: https://informatiestandaarden.nictiz.nl/wiki/FHIR:V1.0_FHIR_Profiling_Guidelines_R4#Slicing maar het is niet duidelijk dat dit een conventie is welke op ieder polymorfisch element dient te worden toegepast. Ook lijkt dit niet in alle profielen te zijn toegepast, waarschijnlijk geldt dit alleen voor de vital-signs profielen.

Acties:
- Richtlijnen aanscherpen
- Checken of alle R4 profielen conform deze richtlijnen zijn gemodelleerd

**Comment by pieter-edelman-nictiz** [comment]
De nut zit hem erin dat het zib-concept op deze manier heel nauwkeurig naar FHIR te mappen is. Volgens mij is dit expliciet zo beschreven in de profiling guidelines:

> Other forms of slicing that are common (Forge sets these slicing details by default): 
> * A concept is mapped to one or multiple types of a polymorphic element, e.g. Observation.value[x]. The mapping and functional description are placed on the slice with the matching data type(s).

De vital signs-profielen zijn een beetje een vreemde eend in de bijt, maar die afwijkingen zijn beschreven en gedocumenteerd. Heb je andere profielen waar dit niet zo wordt toegepast?

**Comment by pieter-edelman-nictiz** [comment]
@LilianMinne , is deze vraag nog relevant?

**Comment by LilianMinne** [comment]
@pieter-edelman-nictiz wat mij betreft kan deze gesloten worden

**Comment by pieter-edelman-nictiz** [comment]
Ok, dank je!
