### ISSUE TITLE
References in zib-extensions verwijzen naar nl-core

### ISSUE THREAD

**Issue by jduwel** [Nictiz/Nictiz-R4-zib2020#304]
Op dit moment verwijzen op een tweetal plekken extensies in de zib-folder (en dus zib-package) naar nl-core targetProfiles. Dit is illegaal vanaf het moment dat de naar 2 gescheiden packages zijn gegaan. Dit moet opgelost worden. De oplossingsrichting is de extensies naar zib-profielen laten verwijzen, die overruled worden in de nl-core profielen.

Daarnaast kunnen de Guidelines aanscherping gebruiken op dit gebied.

**Comment by jduwel** [comment]
@pieter-edelman-nictiz @LuudSlagter Jullie hebben ongetwijfeld nog tekstuele suggesties. Er is in ieder geval iets aan te scherpen.

**Comment by pieter-edelman-nictiz** [comment]
Euh ... ik vraag me af waarom die tekst nodig is. Is dit een andere situatie dan bij de rest van de zib-profielen?

**Comment by jduwel** [comment]
Ja, bij zib-profielen verwijs je naar een zib-profiel en maak je een afgeleid nl-core profiel waarin je de targetProfile overrulet. Bij extensies maak je geen nl-core variant.

**Comment by pieter-edelman-nictiz** [comment]
Ok, ik heb wat schaafwerk gedaan om ook de logica hierachter te verduidelijken.

**Comment by LuudSlagter** [comment]
Ziet er goed uit zo!

**Comment by pieter-edelman-nictiz** [comment]
Geïntegreerd naar prebub
