### ISSUE TITLE
Name/description zib HealthProfessional Reference confusing

### ISSUE THREAD

**Issue by jduwel** [Nictiz/Nictiz-R4-zib2020#306]
https://bits.nictiz.nl/browse/MP-731

Raised by Arianne. The appearance of the `zib HealthProfessional Reference` is confusing in profiles (or in Simplifier at least).
Looking at: https://simplifier.net/packages/nictiz.fhir.nl.r4.medicationprocess9/1.0.0/files/650049
`.requester` - It comes across that being able to reference nl-core-Patient within this zib HealthProfessional Reference is weird, because a Patient isn't a HealthProfessional right?

The text placed in the pattern completely ignores the fact that other resourceTypes may be in the same reference.

**Comment by pieter-edelman-nictiz** [comment]
This has been fixed a while ago by adjusting the title of the profile.
