### ISSUE TITLE
Small textual improvement on root of LaboratoryTestResult

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#311]
https://github.com/Nictiz/Nictiz-R4-zib2020/blob/6143222ceb69fbb66a16f944b5a86cfc710d27af/resources/zib/zib-LaboratoryTestResult.xml#L36

>This concept is represented using `Observation.extension:relatedResult`

The extension in the profile is named sequelTo, not relatedResult.

**Comment by pieter-edelman-nictiz** [comment]
Dit wordt opgepakt via https://bits.nictiz.nl/browse/MM-4984
