### ISSUE TITLE
Slicing .category in profiles

### ISSUE THREAD

**Issue by Ashwin-nictiz** [Nictiz/Nictiz-R4-zib2020#325]
There is a.category element in some profiles. Sometimes we mapped the concept on a slice, and other times we mapped the concept directly on.category. What is the best option? Should we use the slice method in every profile? The medication information standard, for example, is modulated without slices.

**Comment by ArdonToonstra** [comment]
I believe you can achieve similar results with a pattern on the CodeadbleConcept 0..* element (e.g. `Observation.category`) as you could with slicing the CodeableConcept and defining a mandatory slice you would want to have in the instance. I like the cleanness of the first option, but the slicing option may be better in visually guiding the implementer.

**Comment by pieter-edelman-nictiz** [comment]
Performed a few tweaks and merged to the text to prepub.
