### ISSUE TITLE
NL-CM:0.1.32 (DeathIndicator) moet ook gemapt worden op Patient.deceasedDateTime

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#34]
De zib kent zowel een DeathIndicator-boolean als een DateOfDeath. In FHIR mag een van beide aanwezig zijn. De uitleg daarbij is dat als DateOfDeath beschikbaar is, Patient.deceasedDateTime ingevuld moet worden en deceasedBoolean dan geïmpliceerd is. Dat betekent echter dat NL-CM:0.1.32 (DeathIndicator) behalve op Patient.deceasedBoolean ook gemapt moet worden op Patient.deceasedDateTime.

Daarnaast zou ik het commentaar nog iets aanscherpen. Voorstel:
"The zib recognizes both the DeathIndicator (boolean) and DateOfDeath (datetime) concepts, whereas in FHIR only one of these concepts may be present. Therefor, if `deceasedDateTime` (DateOfDeath) is present and has a value, DeathIndicator is assumed to be _true_ as well."

**Comment by jduwel** [comment]
Eens. Zie #20 

De definition of deceasedDateTime is nu volgens de guidelines - maar misschien een beetje vreemd?

**Comment by pieter-edelman-nictiz** [comment]
Ja, dit staat wel raar. Misschien beter om de tweede description weg te halen en het commentaar op deceasesed[x] te verplaatsen naar het commentaar van deceasedDateTime?

**Comment by jduwel** [comment]
Voorstel is dan:
- description en definition terugzetten naar allee DateOfDeath
- mapping wel DeathIndicator geven
- comment deceased[x] verwijderen en comment deceasedDateTime aanpassen naar (ik heb de tekst iets bijgewerkt):
> The zib recognizes both the DeathIndicator (boolean) and DateOfDeath (datetime) concepts, whereas in FHIR only one of these concepts may be present. Therefore, if deceasedDateTime is present and has a value, its value can be mapped to DateOfDeath and DeathIndicator is assumed to be true.

**Comment by pieter-edelman-nictiz** [comment]
Ja, lijkt me goed!

**Comment by pieter-edelman-nictiz** [comment]
Dit is inmiddels doorgevoerd.
