### ISSUE TITLE
zib-Problem misses a ValueSet binding on .bodySite 

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#346]
zib-Problem misses a ValueSet binding on .bodySite  as stated by the AnatomicalLocation profile purpose 
Looked at: https://github.com/Nictiz/Nictiz-R4-zib2020/blob/main/resources/zib/zib-Problem.xml

**Comment by pieter-edelman-nictiz** [comment]
Dit wordt opgelost via https://bits.nictiz.nl/browse/MM-4982
