### ISSUE TITLE
Verwijzing nl-core-HealthcareProvider op Patient.generalPractitioner in nl-core-Patient?

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#36]
Moet aan nl-core-Patient op Patient.generalPractitioner een verwijzing naar nl-core-HealthcareProvider en nl-core-HealthProfessional worden toegevoegd?

**Comment by ArdonToonstra** [comment]
De BgZ heeft de huisarts in scope. Deze wordt via een _include vraagstelling op Patient.generalPractitioner opgevraagd. Dat lijkt me  al voldoende gebruik om in het nl-core-Patient profiel een verwijzing te maken naar de nl-core-HealthcareProvider-Organization én nl-core-HealthProfessional

**Comment by pieter-edelman-nictiz** [comment]
... mits BgZ obv zib2020 dat ook heeft natuurlijk.

**Comment by ArdonToonstra** [comment]
https://www.nictiz.nl/wp-content/uploads/BgZ2020-specificatie-obv-zibs-2020-v1.1.pdf - "Sectie 18.1 Huisarts De gegevens van de huisarts, indien beschikbaar"

Verder is deze er wel bijgekomen volgens mij: "18.2 Zorgverleners De gegevens van alle zorgverleners met een actuele behandelrelatie met de patient, indien beschikbaar"

**Comment by pieter-edelman-nictiz** [comment]
`Patient.generalPractitioner` is een core-element, ik denk dat je die sowieso wil gebruiken als er sprake is van een huisarts, los van de vraag of er andere zorgverleners zijn.

**Comment by ArdonToonstra** [comment]
@pieter-edelman-nictiz , hebben we voldoende om de referentie op te nemen in het nl-core-Patieten profiel en dit issue te sluiten?

**Comment by pieter-edelman-nictiz** [comment]
Yes, ik heb 'em toegevoegd en ik sluit dit issue.
