### ISSUE TITLE
Multiple targetProfiles on slices

### ISSUE THREAD

**Issue by LuudSlagter** [Nictiz/Nictiz-R4-zib2020#365]
Having multiple targetProfiles on slices based on `resolve()` leads to errors of the following form:

_BusinessRule The discriminator path 'resolve()' at http://nictiz.nl/fhir/StructureDefinition/nl-core-MedicalDevice#DeviceUseStatement.reasonReference (DeviceUseStatement.reasonReference:zibMedicalDeviceReference) leads to multiple ElementDefinitions, which is not allowed._

These warnings cannot be ignored, as the Simplifier validator indicates that it does not understand the slicing, since it interprets them as ambiguous. 

Allowing multiple targetProfiles is a deviation of how e.g. fixed/value discriminators work: you can only have _one_ fixed value. With a type discriminator, you can only have a _single_ type. So it would be a deviation to allow multiple profiles here. In fact, in the notes after https://build.fhir.org/profiling.html#discriminator it says: 

_With regard to the use of `resolve()`, (...) and it is in the profile that **the** `targetProfile` refers to where a fixed value or pattern for the element must be declared. **The** targetProfile itself is declared in the element in the slice that immediately precedes the resolve() function in the discriminator path (e.g. 'item' in item.resolve().name), and that element is the final element that the slice declares._

Although not really explicit, most of the text is talking about a single targetProfile, just like a single fixed value. So, the validator used by Simplifier does not support having multiple possibilities (which would mean an OR in the discriminator condition). Now, it's not to say this cannot be done, and it would definitely not be a simple fix, since the assumption of a single condition per slice discriminator is a pretty deeply embedded assumption in the validator. 

It's worth double checking on Zulip on whether this allowed (the fact that the other validator does not complain does not mean it supports it - although that's probably easy to check).

**Comment by pieter-edelman-nictiz** [comment]
This issue has been handled and the profiling guidelines now state that just a single targetProfile may be present on a slice.
