### ISSUE TITLE
Patient.contact.address heeft een te beperkte kardinaliteit

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#37]
zib ContactPerson is _ook_ gemapt op `Patient.contact`. De zib schrijft voor AddressInformation een kardinaliteit voor van 0..*. `Patient.contact.address` heeft echter een kardinaliteit van 0..1.

FHIR beargumenteert dit met: "Need to keep track where the contact person can be contacted per postal mail or visited.". Het gaat dus om een adres specifiek voor de use case "contactpersoon van de patient". In die zin is het wel logisch dat je niet drie verschillende adressen wil hebben in deze context. Aan de andere kant: een apart post- en bezoekadres zijn natuurlijk best mogelijk.

Hoe gaan we hiermee om? Alleen een uitleg dat we hier afwijken van de zib en dat de volledige gegevens van de contactpersoon in de RelatedPerson-resource gevonden kunnen worden? Of moeilijk doen met extensies om wél aan de zib te kunnen voldoen?

**Comment by jduwel** [comment]
In het kader van 'volledige gegevens in RelatedPerson' zou deze wel eens van pas kunnen komen: http://www.hl7.org/fhir/extension-patient-relatedperson.html

**Comment by pieter-edelman-nictiz** [comment]
Oh ... goed gevonden!

**Comment by ArdonToonstra** [comment]
Wow, idd een goede vonst! Dus die uitleg plus die extensie toevoegen?

Lijkt me beter dan zelf iets met extensies te doen.

**Comment by pieter-edelman-nictiz** [comment]
Komt die extensie dan "in plaats van" of "in aanvulling op"?

**Comment by ArdonToonstra** [comment]
In aanvulling op zou ik zeggen. Anders sturen we nog meer op duplicatie van gegevens. Bij de BgGGZ worden alleen eerste contactpersonen in de dataset geïncludeerd. Dit verloopt dan alleen via de Patient.contact. Waarschijnlijk kom je in de meeste gevallen wel weg met een 0..1 adres, denken we niet?

**Comment by pieter-edelman-nictiz** [comment]
Als je duplicatie wil voorkomen, dan is "in plaats van" toch beter?
Wat bedoel je met "eerste contactpersoon"? Volgens de zib is een contactpersoon dat "iedereen die gerelateerd is aan de patient". Volgens FHIR is dat "iemand die gecontacteerd moet worden mbt. behandeling van de patient". Dat maakt de discussie extreem lastig.
Ik zou het logisch vinden om zib ContactPersoon altijd alleen te vertalen naar FHIR RelatedPerson. Met de extensie in Patient kan je dan aangeven: deze RelatedPerson en een FHIR contact van de Patient. Dan heb je geen duplicatie van content.

**Comment by ArdonToonstra** [comment]
Ah, als in de gehele Patient.contact niet te gebruiken? Ik zat met mijn hoofd alleen nog bij het wel/niet vullen van de address. Nog niet dat we Patient.contact niet gebruiken.

Maar er nog eens over nadenken is dat wellicht helemaal geen slecht idee. Wordt het wel weer een stuk eenduidiger van én als use cases toch Patient.contact willen gebruiken kan dat natuurlijk als nog.

**Comment by pieter-edelman-nictiz** [comment]
Precies, die extensie staat op `Patient.contact`, dus die zou de inhoud ervan kunnen vervangen. Weet niet zeker of dat dat de bedoeling is, maar het lijkt me een betere optie uiteindelijk.

**Comment by ArdonToonstra** [comment]
Lijkt me sowieso iets om bij een breder publiek te toetsen: door bij consultatie / validatie deze wijziging duidelijk aan te kaarten of door actief input te vragen.

**Comment by pieter-edelman-nictiz** [comment]
Ja, dat geldt voor een hoop dingen ...

**Comment by jduwel** [comment]
Hoewel ik zelf meer neig naar 'gegevens op maar 1 plek' en dus alles in RelatedPerson en Patient.contact niet gebruiken, doet de tekst van de extensie vermoeden dat hij bedoeld is om alleen te koppelen als beide bestaan. Dus we zouden de extensie enigzins misbruiken denk ik

**Comment by pieter-edelman-nictiz** [comment]
Pull request met de beoogde oplossing aangemaakt.

**Comment by pieter-edelman-nictiz** [comment]
@ArdonToonstra , @jduwel , zouden jullie hier nog naar kunnen kijken? Dan kunnen we dit issue afsluiten.

**Comment by jduwel** [comment]
Niets aan toe te voegen

**Comment by ArdonToonstra** [comment]
@pieter-edelman-nictiz , ook niets aan toe te voegen. Pull request m.b.t de modelering en documentatie van Patient.contact ziet er top uit.
