### ISSUE TITLE
Hoe moeten referenties naar zib HealthProfessional gemaakt worden?

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#41]
Zib HealthProfessional kent twee profielen: zib-HealthProfessional-Practitioner en zib-HealthProfessional-PractitionerRole. In principe zou je een referentie altijd (alleen) op zib-HealthProfessional-PractitionerRole willen hebben, want van daar kom je bij zib-HealthProfessional-Practitioner.
Het is echter in principe mogelijk om een instance van zib-HealthProfessional-Practitioner te maken zonder zib-HealthProfessional-PractitionerRole. In dat geval zou je dus wél direct naar zib-HealthProfessional-Practitioner willen refereren.

Hoe moeten we dit soort referenties opnemen in de profielen?
* Alleen een referentie naar zib-HealthProfessional-PractitionerRole toevoegen**? De base Practitioner blijft aanwezig, dus een referentie naar een instance van het zib-HealthProfessional-Practitioner-profiel blijft gewoon mogelijk. Dit maakt de aanpak echter niet heel duidelijk voor implementers.
* Referenties naar beide profielen toevoegen? De referentie is meestal 0..1, dus de implementer zal één van beide instances moeten kiezen, wat normaal de zib-HealthProfessional-PractitionerRole instance is, maar zib-HealthProfessional-Practitioner kan zijn als de eerste er niet is. Dit kan echter weer verwarring scheppen bij implementers wat ze nu normaliter moeten gebruiken.
* Een van beide opties en in tekst uitleg toevoegen bij elke referentie?
* Een van beide opties en in tekst uitleg toevoegen in de twee zib-HealthProfessional-profielen?

** NB. In de profiling guidelines voor FHIR R4 is besloten om referenties niet te constrainen op het doelprofiel, maar om het doelprofiel toe te voegen aan de lijst met base-resources.

**Comment by ahenket** [comment]
> Het is echter in principe mogelijk om een instance van zib-HealthProfessional-Practitioner te maken zonder zib-HealthProfessional-PractitionerRole. In dat geval zou je dus wél direct naar zib-HealthProfessional-Practitioner willen refereren.

`Practitioner` is eigenlijk meer een persoon dan een zorgverlener als je kijkt naar de eigenschappen in die resource. Er zit geen specialisme, geen relatie naar zorgaanbieder: dat is allemaal `PractitionerRole`. Ik heb eigenlijk geen voorstelling bij de use cases die we zouden dienen bij een directe referentie naar `Practitioner`. Behalve dat het 'in principe' mogelijk is: wat zou dat dan betekenen? 

- Iets als 'huisarts Jansen' is al meteen een voorbeeld. Specialisme "huisarts" is `PractitionerRole.specialty` terwijl "Jansen" `Practitioner.name` is, verbonden via `PractitionerRole.practitioner`. Een directe verwijzing naar `Practitioner` levert dus alleen "Jansen". 
- Iets als 'huisarts bij huisartsenpraktijk Jansen' is ook een voorbeeld. Specialisme "huisarts" is `PractitionerRole.specialty` terwijl "huisartsenpraktijk Jansen" de `Organization.code` + `.name` is, verbonden via `PractitionerRole.organization`. Een directe verwijzing naar `Practitioner` levert dus ... niks. 

Bestaan die use cases voor een direct `Practitioner` dus wel? Bij `Patient.generalPractitioner` zou je nog kunnen beargumenteren dat het specialisme van de `Practitioner` blijkt uit de koppeling via `.generalPractitioner` maar dat voelt als erg twijfelachtige argumentatie.

Het tegenargument is dat de meeste systemen die ik ken niet die scheiding tussen `PractitionerRole` en `Practitioner` onderkennen en dus speciaal voor FHIR iets kunstmatigs aan het doen zijn, omdat het in FHIR niet anders kan (daar is overigens best discussie over geweest door de tijd heen via Thomas Beale uit de openEHR hoek).

Ik denk dat systemen die formeel eigenlijk geen twee separaat beheerde objecten (`PractitionerRole` en `Practitioner`) hebben, zouden moeten werken met `PractitionerRole` met daarin een `.contained.Practitioner`. Dan hoef je in elk geval niet te doen alsof.

Terug naar de vraag:

Ik denk dat toen in R4 `PractitionerRole` werd toegevoegd er scherper gekozen had kunnen worden door `Practitioner` tevens weg te halen. Ik zou voor de NL profielen dan ook willen sturen op `PractitionerRole` als er theoretisch een keuze ligt tussen `PractitionerRole` en `Practitioner`.

Je vraag is gebaseerd op het feit dat we onder de huidige [Profiling Guidelines](https://informatiestandaarden.nictiz.nl/wiki/FHIR:V1.0_FHIR_Profiling_Guidelines_R4#Constraining_references), `Practitioner` niet zouden verwijderen en dus de situatie houden dat iemand `Practitioner` zou kunnen kiezen waar wij `PractitionerRole` zouden prefereren.

Als we in dat soort gevallen, `PractitionerRole` aankleden met nl-core-practitionerrole en bijschrift van bovenstaande strekking en verder geen directe aandacht besteden aan `Practitioner` in de differential, dan zou mijn verwachting zijn dat mensen in de richting van richting van `PractitionerRole` worden gestuurd zonder dat een use case voor `Practitioner` - waar ik me nu even niks bij kan voorstellen - onmogelijk wordt gemaakt.

Op zichzelf sta ik overigens wel open voor expliciet schrappen van de `Practitioner` optie en dat documenteren in de _profiling guidelines_ ten behoeve van vermindering van _keuzestress_. Dat betekent dan wel dat er echt geen valide use case moet zijn om `Practitioner` te willen gebruiken. 

Vergelijkend incompleet warenonderzoekje levert dat internationaal de keuze `Practitioner` in elk geval **niet** wordt geschrapt:

- [AU Core](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicationrequest.html) heeft beide actief onder `MedicationRequest`
- [US Core](http://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-careteam.html) heeft beide actief onder `CareTeam` en mustSupport op Practitioner
- [SDC](http://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-task.html) heeft beide actief op `Task`
- [HL7 IPS](http://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Composition-uv-ips.html) heeft beide actief op `Composition`

**Comment by mmsmits** [comment]
Wat als ik alleen maar naar een AGB, UZI of BIG wil verwijzen? Moet dit dan via een lege PractitionerRole?

**Comment by ahenket** [comment]
Ja, dat zou inderdaad het gevolg zijn. Je krijgt dan iets als onderstaande. Het voordeel van dit construct is wel dat als je wel het specialisme of zorgaanbieder wilt communiceren, je die er gewoon bij kunt zetten in PractitionerRole zonder dat je eerst een ommezwaai van Practitioner naar PractitionerRole hoeft te maken (als zender en ontvanger). Het is een afweging.

@mmsmits: wat zou jouw afweging zijn?

```
<Observation xmlns="http://hl7.org/fhir">
    <id value="obs1"/>
    <!-- contained is slechts voorbeeld, geen verplichting of wenselijkheid -->
    <contained>
        <PractitionerRole xmlns="http://hl7.org/fhir">
            <id id="practrole1"/>
            <practitioner>
                <reference value="Practitioner/pract1"/>
                <display value="UZI: 000432123"/>
            </practitioner>
        </PractitionerRole>
    </contained>
    <!--...-->
    <performer>
        <reference value="#practrole1"/>
        <display value="UZI: 000432123"/>
    </performer>
</Observation>

<!--...-->

<Practitioner xmlns="http://hl7.org/fhir">
    <id value="pract1"/>
    <identifier>
        <system value="http://fhir.nl/fhir/NamingSystem/uzi-nr-pers"/>
        <value value="000432123"/>
    </identifier>
</Practitioner>
```

**Comment by weteringac** [comment]
Rendering your practitioner the same way regardless of how much you know / want to convey does have advantages for interoperability: you know what to expect and you only need one parsing method.

**Comment by mmsmits** [comment]
Ja ik snap je punt, als je altijd via PractitionerRole moet, weet je als implementer altijd waar je de info moet zoeken. Ik kan me er in vinden dat de "ingang" naar de Zib HealthcareProvider, altijd via PractitionerRole is, zodat je verwarring (en onnodig veel code) bij de implementer weghaalt.

Toch zou ik oppassen en de Practitioner references niet helemaal weggooien (open world), maar misschien niet de zib-HealthcareProvider (of nl-core-practitioner) toevoegen. Dan geef je de implementer het goede voorbeeld, zonder dat je dingen ongemogelijk maakt.

In ieder geval goed voer voor een mooi stuk duidelijke en goed vindbare documentatie ergens. (Misschien zelfs direct in de PractionerRole en Practitioner profiles) wat er verwacht wordt,

Ik zal collega's die hiermee bezig zijn bij LUMC en EMC ook even op dit gesprek wijzen. Zij kunnen beter zeggen of dit haalbaar/makkelijker/moeilijker is.

**Comment by LilianMinne** [comment]
@mmsmits bedankt voor het wijzen op deze discussie.

HiX kent inderdaad geen onderscheid tussen Practitioner en PractitionerRole. Er is een enkele artsentabel waarin artsen meerdere records kunnen hebben per rol die ze binnen het ziekenhuis uitoefenen. Alles wat zij registreren is gekoppeld aan deze rol en dus PractitionerRole en niet Practitioner. Binnen het LUMC en UMCU zijn we dus blij met de extensie voor PractitionerRole en deze wordt veelvuldig gebruikt, de referentie naar Practitioner wordt meestal nog leeggelaten.

Dit omdat het vullen van het Practitioner model de nodige complexiteit geeft. Zoals gezegd kan de HiX artsentabel meerdere records per persoon bevatten en de data in deze tabel is te beperkt om deze te 100% op een betrouwbare manier te kunnen 'ontdubbelen'. Zo kan de naam net anders geschreven zijn en ontbreekt voor interne artsen de geboortedatum, omdat deze alleen in het personeelsysteem geregistreerd staan. 
Ook is gekeken of het personeelsysteem als uitgangspunt gebruikt kan worden, maar dan mis je de externe artsen en er is ook geen eenduidige scheiding te maken in de HiX artsentabel tussen interne en externe artsen. Inmiddels is er wel een project gaande, waarbij een personeelsnummer in de HiX artsentabel gevuld gaat worden voor alle artsen, waarmee gekoppeld kan worden aan de data in het personeelsysteem. Dit hebben we dan weer nodig om BIG en AGB registraties voor interne artsen op te kunnen halen. Voor externe artsen zijn deze gegevens gevuld in HiX, maar dat geldt (in elk geval voor het LUMC) niet voor interne artsen.

Uiteindelijk zullen we het model Practitioner wel nodig gaan hebben voor authorisatie doeleinden, maar voor de referenties vanuit geregistreerde zorgdata hebben we dus (momenteel) geen use cases. Maar ik zou inderdaad wel voorzichtig zijn met deze aanname en het volledig constrainen van de Practitioner reference. 
Ik kan me wel vinden in het voorstel van Marten om alleen nl-core-practitioner weg te halen zonder Practitioner volledig weg te gooien. Dan is het duidelijk wat de voorkeur heeft, maar maak je het niet onmogelijk voor de implementer. 
En daarnaast inderdaad goede documentatie toevoegen in de IG. Ook tekst uitleg bij elke referentie en tekst uitleg in de twee zib-HealthProfessional-profielen lijken me beide van toegevoegde waarde.

Wat betreft het meesturen van contained resources, dit maakt de implementatie voor de genoemde huizen een stuk complexer en zou ook niet mijn voorkeur hebben.

**Comment by ahenket** [comment]
Ik lees een redenatie richting:
- `PractitionerRole` en `Practitioner` beide laten staan
- profiel nl-core-practitionerrole toevoegen
- profiel nl-core-practitioner _niet_ toevoegen
- goed documenteren (mede op basis van dit issue) wat je geacht wordt te doen en daar alleen onder gedocumenteerde omstandigheden van af te wijken (_comply or explain_)

Het wordt wel even puzzelen hoe/waar je dat documenteert. Om in iedere van de vele profielen die dit betreft dezelfde tekst te kopiëren, klinkt niet efficiënt. Misschien kan dit in een FHIR Profiling Guidelines-paragraaf waarnaar al die resource kunnen refereren.

**Comment by pieter-edelman-nictiz** [comment]
@ahenket volgens mij klopt je analyse. We zullen een custom extension genaamd explanationAboutReferencingZibHealthcareProvider maken en die overal toevoegen /s

**Comment by MartinaHoeverFurore** [comment]
In het Erasmus MC is de situatie vergelijkbaar met de situatie die Lilian beschrijft, al hebben wij de artsen uiteindelijk wel redelijk uniek in als persoon Practitioner kunnen krijgen. Wij verwijzen nu vanuit de meeste profielen zowel naar Practitioner als naar PractitionerRole, vooral om te voldoen aan de standaard waar de verwijzing naar Practitioner in zit, maar ook de toegevoegde waarde van PractitionerRole niet te missen.

De redenatie richting die hierboven genoemd wordt lijkt mij de juiste oplossing. Duidelijk en consequent als we dit in de verschillende profielen gelijktrekken. Het is voor ons geen probleem om via PractitonerRole te moeten gaan om bijvoorbeeld de AGB, UZI of BIG te tonen zoals Marten zich hierboven afvroeg.

**Comment by pieter-edelman-nictiz** [comment]
Richtlijnen worden uitgewerkt op https://informatiestandaarden.nictiz.nl/wiki/FHIR:Vissue-Github-41_FHIR_Profiling_Guidelines_R4

**Comment by pieter-edelman-nictiz** [comment]
Een datatype-profiel is gemaakt en de documentatie is opgenomen in de profiling guidelines. Ik sluit dit issue.
