### ISSUE TITLE
Update ext-Comment context from Resource.descendants() to Element

### ISSUE THREAD

**Issue by ahenket** [Nictiz/Nictiz-R4-zib2020#427]
After testing with the Java validator with [ext-Comment](https://github.com/Nictiz/Nictiz-R4-zib2020/blob/d078858a3c50b1769248f4a984389eb9d5f70209/resources/zib/ext-Comment.xml#L28) and a round on [Zulip](https://chat.fhir.org/#narrow/stream/179239-tooling/topic/Validator.20support.20for.20Resource.2Edescendants.28.29.3F) I found that it does not support context `Resource.descendants()`. A slight adjustment would do the trick:

Change
```xml
<context>
  <type value="fhirpath" />
  <expression value="Resource" />
</context>
<context>
  <type value="fhirpath" />
  <expression value="Resource.descendants()" />
</context>
```

to
```xml
<context>
  <type value="fhirpath" />
  <expression value="Resource" />
</context>
<context>
  <type value="fhirpath" />
  <expression value="Element" />
</context>
```

According to the Zulip replies from Lloyd and Grahame you could even remove the context on `Resource`.

**Comment by pieter-edelman-nictiz** [comment]
Continued in https://bits.nictiz.nl/browse/MM-5127
