### ISSUE TITLE
nl-core pkg abstraction

### ISSUE THREAD

**Issue by LuukBerkel** [Nictiz/Nictiz-R4-zib2020#437]
# nl-core pkg abstraction
During my research on the models for zib2020 for FHIR I came acros a problem. 
In het documentation is written that the zib2020 package is not suitable for implementation and the nl-core package is. 

But the problem is that the nl-core package is an abstraction. Take for example the profile NameInformation. If you look at this profile on nl-core, you will be able to see that it is missing fields. But these fields are filled in on the zib2020 package. This fine over all but it raises a few questions. 

## Profile Name Information on nl-core package
https://simplifier.net/packages/nictiz.fhir.nl.r4.nl-core/0.10.0-beta.1/files/2195036
## Profile Name Information on ZIBS package
https://simplifier.net/packages/nictiz.fhir.nl.r4.zib2020/0.10.0-beta.1/files/2194798

Does this mean we need to fill those profiles abstract profiles on our own? How can it be standard with other implementations then if you can give it your own spin? 
![afbeelding](https://github.com/Nictiz/Nictiz-R4-zib2020/assets/74413450/662ff146-f114-4a6a-bc76-351948db5bc8)

Sorry if this was the wrong place to ask, but i did not find a forum on this repo. 
Thanks in advance.

**Comment by pieter-edelman-nictiz** [comment]
Hi @LuukBerkel ,
The nl-core layer is not an abstraction of the zib layer. The zib layer is "abstract", meaning the same as in OO programming: it is a base that is not directly implementable, but meant as a base for a concrete implementation. The nl-core layer is this concrete implementation; they are derived from the zib profiles, which means that everything present in the zib profiles is also present in the nl-core profiles.
So I'm wondering: what fields are you missing?

**Comment by LuukBerkel** [comment]
Hi @pieter-edelman-nictiz, 

Thanks for your response. I seem to have made a mistake in viewing the profiles on simplifier.net.
The problem was that the website simplifier,net opens the profiles standard on diff mode, and since it is based on the zib2020 package i only saw the difference and not the whole profile. That was why there were fields missing. 

![afbeelding](https://github.com/Nictiz/Nictiz-R4-zib2020/assets/74413450/f465d190-5d7e-40c4-a6ef-1eebab54d8b8)

This means that there is no issue now,  and so I will close it.
