### ISSUE TITLE
nl-core profiles not published in package?

### ISSUE THREAD

**Issue by vadi2** [Nictiz/Nictiz-R4-zib2020#439]
How come the implementable `nl-core` profiles are not published in [nictiz.fhir.nl.r4.zib2020](https://simplifier.net/packages/nictiz.fhir.nl.r4.zib2020/)? This makes validation of instances against the package more challenging.

**Comment by pieter-edelman-nictiz** [comment]
Hi @vadi2 , the nl-core profiles are published in a separate derived package: nictiz.fhir.nl.r4.nl-core

**Comment by vadi2** [comment]
That makes sense - thanks!
