### ISSUE TITLE
Mandatory FHIR elements (e.g. Resource.status) not mapped to a zib concept

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#45]
FHIR resources often have mandatory elements, like `Resource.status`, that do not have a mapping to a concept defined by the zib. Sometimes these mandatory elements are useful and are tracked/captured in systems However, on some occasions, systems don't track or capture the information required by the mandatory element.  A consistent approach would be favourable, hence this issue to determine the best approach. Options:

1. Describe a generic escape method, using e.g. data-absent-reason extension, on the implementation guide level. Don't add the extension to every mandatory element in FHIR.
2. Option 1 and make the extension explicit in the FHIR profiles for mandatory elements where it is expected that systems might not be able to provide the required information.
3. Option 1 and place a comment/documentation on the mandatory elements with guidance. 
4. Leave it to FHIR, don't do anything extra and let implementers find the right information based on the FHIR spec definition.

**Comment by pieter-edelman-nictiz** [comment]
I think the first consideration should be if it's possible to "map" the required element to the zib concepts. For example, a `.status` might be inferred from an end date present in the zib.

Apart from that, I think the escape should really be an escape and that systems should do their best to align with the intention of FHIR. Therefore, I would go for a description in the implemention guide.

**Comment by pieter-edelman-nictiz** [comment]
NB. When "mapping" zib elements to these required elements, the mapping comment can be used to make clear that it is for example a "partial" or "derivative" mapping.

**Comment by Ashwin-nictiz** [comment]
I think Pieter's description in the implementation guide is a 'safe' solution for this. The description must be clear and well described for the implementer.

**Comment by ArdonToonstra** [comment]
I agree that the escape should only be an escape and we should therefore not explicitly profile it. The implementation guide would be more suited.

>NB. When "mapping" zib elements to these required elements, the mapping comment can be used to make clear that it is for example a "partial" or "derivative" mapping.

I think this is a good additional guideline we can incorporate in the Profiling Guidelines. 

>I think the first consideration should be if it's possible to "map" the required element to the zib concepts. For example, a .status might be inferred from an end date present in the zib.
I wonder if we can easily make those mappings for most zibs. If we can, shall we document it in the required element's comment? Would be nice if this can be added like a ConceptMap kind of resource.

**Comment by pieter-edelman-nictiz** [comment]
FHIR is a standard for health care data _exchange_, not _storage_. In theory, all FHIR systems should be able to dynamically edit a resource according to the situation. Of course, in practice things might be different, but I would suggest to turn the argument inside out; systems that _cannot_ dynamically populate the {{.status}} might resort to data-absent excuses.

**Comment by jduwel** [comment]
In addition to this:
TextResultStatus and Observation.status both have 1..1 cardinality, but because of conceptual cardinality 0..1 is expected in FHIR. The outcome of this dicussion could be (should be?) applicable to this situation as well.

**Comment by jduwel** [comment]
I would propose Option 1 because of the following:

Option 2: I could imagine use cases where it is valuable or necessary to add data-absent-reason to a not-required element if needed. If we explicitly add the extension on specific elements, do we implicitly exclude it from being present in other elements?

Option 3: Repeats information

Option 4: "the right information" in the FHIR spec would still lead to two options (data-absent-reason and nullFlavor). Receiving systems would need to implement both (and: without our guidance) if we don't document anything.

If we would go for option 1, we still have a decision to make whether to favor https://www.hl7.org/fhir/extension-data-absent-reason.html or http://www.hl7.org/fhir/extension-iso21090-nullflavor.html. Anyone working with v3 and/or mappings would probably prefer the latter, I think when working from ART-DECOR it is a more natural fit. FHIR-only perhaps prefers the former? I do think it is a plus that Observation.dataAbsentReason uses the same ValueSet as the extension.

Next to that: in cases where conceptual cardinality comes in as described above, I would still point to an IG how to handle this. If an informationstandard wants to specifically exclude the element in their profile, only then the explicit profiling of the extension comes in.

**Comment by ArdonToonstra** [comment]
I agree with the argumentation of Jorn and would like to move on with option 1.

Regarding:
>... favor https://www.hl7.org/fhir/extension-data-absent-reason.html or http://www.hl7.org/fhir/extension-iso21090-nullflavor.html. Anyone working with v3 and/or mappings would probably prefer the latter, I think when working from ART-DECOR it is a more natural fit. FHIR-only perhaps prefers the former? I do think it is a plus that Observation.dataAbsentReason uses the same ValueSet as the extension.

Good point. I am leaning towards the data-absent-reason extension. Also because the comment on the nullflavor extension states:

>Considerable care must be used when using nullFlavor in this context of FHIR - more than any other concept, this is tied to the way v3 works, and FHIR is quite different. For instance, there is no notion of a "proper value" as opposed to any other value in FHIR. a NullFlavor should be understood to mean, "why information is missing", and the nulFlavors OTH, NINF, PINF, and TRC should not be used.

**Comment by jduwel** [comment]
@pieter-edelman-nictiz Yes I actually assumed this to be the way to go.

**Comment by ArdonToonstra** [comment]
>I think the first consideration should be if it's possible to "map" the required element to the zib concepts. For example, a .status might be inferred from an end date present in the zib.

@pieter-edelman-nictiz  agree. Do we be default need to provide guidance on this in the profiles with regards to the zib concepts that may have a relation with the mandatory elements? Perhaps also here a sentence or two in the IG/profiling guideline will suffice?

**Comment by pieter-edelman-nictiz** [comment]
Proposal for addition to profiling guidelines:

# In chapter 10, add a section "Mandatory FHIR elements without a functional counterpart", with the following text:

On occasion, FHIR requires an element to be populated while the functional model doesn't specify it. For example, the Procedure resource has the required element `Procedure.status`, but the zib Procedure, which is mapped to this FHIR resource, doesn't specify such a field.

In these circumstances, an effort should be made to map the zib concepts _implictly_ to these elements. For example, FHIR `Procedure.status` can be inferred from the zib concept ProcedureEndDate; if it is in the past, then the status should be assumed to be _completed_. If it is not possible to make such an implicit mapping, the FHIR element is left as-is; the implementation guide should describe how the implementer should deal with it, probably using the data-absent-reason extension.

Implicit mappings are documented in the following way:
* The `comment` of the implicitly mapped element should provide guidance on how to map the functional concept.
* The `mapping` element is populated with the mapped concept, but the description is altered to: "If the mapping is an implicit mapping to a required FHIR element, `mapping.comment` will be "[concept name] (implicit, main mapping is on `[element name]`)".

# In section 3.3.1 (Associating the functional definition to StructureDefinitions/Current implementation), add the following paragraph:

Note that implicitly mapped elements use a slightly different description.

# In section 10.2.1.2 (Metadata for elements), change:
"For elements that map to zibs" into "For elements that map directly (not implicitly) to zib components"

**Comment by ArdonToonstra** [comment]
>The mapping element is populated with the mapped concept, but the description is altered to: "If the mapping is an implicit mapping to a required FHIR element, mapping.comment will be "[concept name] (implicit, main mapping is on [element name])".

I like the use of `mapping` to document the implicit mapping, including the suggested boiler text. However, will this result in adding more lines in known-issues.yml?

**Comment by pieter-edelman-nictiz** [comment]
This is undesirable of course, the tooling should account for this.

**Comment by pieter-edelman-nictiz** [comment]
Added this to the profiling guidelines. I'll leave the issue open because the tooling still needs to be adjusted,

**Comment by jduwel** [comment]
https://informatiestandaarden.nictiz.nl/wiki/FHIR:V1.0_FHIR_Profiling_Guidelines_R4#Mandatory_FHIR_elements_without_a_functional_counterpart and #79

**Comment by jduwel** [comment]
Was in doubt to create a new issue, but since this is related:

What to do in the ada2fhir mappings on these elements?
For example: Encounter.status should have an implicit mapping (will add that soon), one could base it on period.start and/or .end. However, one could argue that the context of the ada2fhir transformation is inherently unknown, therefor the .status should be fixed to 'unknown' in the ada2fhir mapping. One cannot know how much time passes between conversion and sending/receiving the message. However, you could also say that this approach is too lazy, but then it could be that for each ada2fhir mapping where this is needed, you need some custom logic.
