### ISSUE TITLE
Use of Observation.component

### ISSUE THREAD

**Issue by jduwel** [Nictiz/Nictiz-R4-zib2020#58]
A piece of text should be added to https://informatiestandaarden.nictiz.nl/wiki/FHIR:V1.0_FHIR_Profiling_Guidelines_R4#Zib_2020_specific_considerations to justify the mapping of Measurement zib concepts to Observation.component of to other elements. Based on my experience with BloodPressure, I've tried to compose a paragraph:

> Measurement zibs that are mapped on the FHIR Observation resource often include concepts that contain ancillary data and that are not directly results of the observation or measurement. If it is not possible to map these concepts to an equivalent element or to a core extension of Observation, these concept may be mapped to `Observation.component`, following a remark in the specification ("[or may provide qualifying information to Observation.code](https://www.hl7.org/fhir/observation.html#gr-comp)") and [discussion on Zulip](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Pathology.20Lab.20Reports.20.E2.80.93.20Dynamic.20Function.20Tests.20.2F.20Timed.20Tests/near/227279594) that the use of `component` for qualifiers is appropriate and preferred above (custom) extensions.

**Comment by pieter-edelman-nictiz** [comment]
I'm not sure if this is a zib specific issue actually.

**Comment by pieter-edelman-nictiz** [comment]
Even zitten schaven:
> Functional models for measurements will usually be mapped onto the FHIR Observation resource. The type of measurement is conveyed using `Observation.code` and the result of the measurement is conveyed using `Observation.value[x]`, or `Observation.component.value[x]` if the measurement consists of multiple components.

>  However, sometimes the functional model requires that the type of measurement needs to be further specified using a qualifier. For this purpose, the `Observation.method` and `Observaton.bodySite` elements can be used. If it is not possible to map these concepts to these elements or to a core extension of Observation, they may be mapped to `Observation.component`, according to a remark in the specification ("[or may provide qualifying information to Observation.code](https://www.hl7.org/fhir/observation.html#gr-comp)") and a [discussion on Zulip](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Pathology.20Lab.20Reports.20.E2.80.93.20Dynamic.20Function.20Tests.20.2F.20Timed.20Tests/near/227279594), which concludes that the use of `component` for qualifiers is appropriate and preferred above (custom) extensions.

**Comment by ArdonToonstra** [comment]
Voorgestelde tekst ziet er goed uit. Ik zou alleen de link naar FHIR alvast vastzetten op r4: https://www.hl7.org/fhir/r4/observation.html#gr-comp

**Comment by pieter-edelman-nictiz** [comment]
Dan zou ik willen voorstellen om sectie 11 in de profiling guidelines een beetje om te gooien in:

11. Special considerations
11.1 Use of FHIR resources
11.1.1 Measurement qualifiers in Observation.component
11.1.2 FHIR Vital Signs compatibility
11.2 Zib 2020 specific considerations
[...]

**Comment by mvdzel** [comment]
Some thoughts:
1. the Observation.value[x] should be used for the "main" value and the component.value[x] for "supporting" values, for weight that is obvious, but for bloodpressure this is difficult because there are 2 "main" values. In that case I would put all values in component.value and maybe some kind of composed value in observation.value, a string "130/80".
2. Take the SCT mappings into account http://hl7.org/fhir/observation-mappings.html#sct-attr, so check if the code is the same or compatible with the sct code in the zib

**Comment by pieter-edelman-nictiz** [comment]
Hi @mvdzel , this issue is more about the definition than the result of the measurement. For zib BodyWeight the state of clothing is not something that you measure, it's something that you need to know about the measurement. There seems to be a consensus that this can also be captured using `Observation.component`.

**Comment by mvdzel** [comment]
@pieter-edelman-nictiz That is exactly what I mean by "supporting" values, that go in an existing element (like bodySite) or Observation.components, but you have to use the right codes there (#2).
And by "main" value I mean the thing that is measured and that go into Observation.value.
I think we agree?!

**Comment by jduwel** [comment]
(Re: composing component values in `value[x]`) Using multiple components and leaving `value[x]` empty is agreed to be a valid solution to this (http://hl7.org/fhir/R4/observation.html#gr-comp). If we approach the problem from a perspective "how could we highlight which `component` is/are the 'main' values", then maybe we are onto something, but a) duplicating data is not really a solution in my opinion (if the 'main' data itself is not exclusively available in extensions) and b) how big of a problem is this when there are IGs and models to guide you on interpreting a profile.

(Re: mappings) @mvdzel did you mean to link to http://hl7.org/fhir/observation-mappings.html#sct-concept ? This would be an interesting check I guess. Could help to determine if a zib concept is a fit or not (or to check afterwards). This discussion started from a point of view "can we map concepts to `components` that are not really "component observations"?. I don't know if it helps us answering this question. And then there are situations where (for example) HL7 Vital Signs maps a concept to `component` when there is a core element (or core extension) available (see also #62).

**Comment by pieter-edelman-nictiz** [comment]
So ... I think it's clear then? The main value goes into `Observation.value[x]`, and any supporting measurement _or_ qualifier can go in `Observation.component`, properly coded. When there isn't a single main value, all value go into `Observation.component`.

**Comment by ArdonToonstra** [comment]
>The main value goes into `Observation.value[x]`, and any supporting measurement or qualifier can go in `Observation.component`, properly coded. When there isn't a single main value, all value go into `Observation.component`.

Yes, I think this is it.

**Comment by pieter-edelman-nictiz** [comment]
Still need to add this to the profiling guidelines, so I'm reopening the issue.

**Comment by pieter-edelman-nictiz** [comment]
Added this to the profiling guidelines.
