### ISSUE TITLE
Is the FHIR markdown datatype a proper implementation of ST?

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#60]
Currently, the zib datatype _ST_ is mapped to FHIR datatype _string_, according to the profiling guidelines. However, a lot of the textual FHIR elements are of the _markdown_ datatype. Can we safely map _ST_ to _markdown_ as well? In theory, Markdown _is_ just flat text that may be rendered somewhat nicer. It is extremely unlikely that the fact that the text in interpreted as Markdown will mess up the text.

If we agree that _ST_ can be mapped to _markdown_, this should be added to the profiling guidelines and to the zib compliance tool.

**Comment by jduwel** [comment]
There is a risk that when exporting data (to v3 for example) markdown syntax will end up in a string. This leads to unexpected but non-critical results. Markdown syntax processing is optional according to the spec: https://www.hl7.org/fhir/datatypes.html#markdown, so exported text will still be understandable, only somewhat harder to read perhaps.

**Comment by pieter-edelman-nictiz** [comment]
Yes, that's basically the point of Markdown. 

In addition, you can make the point that the zib compatibility only goes one way; the profile guarantees that all information from the zib can be captured in a FHIR instance, but the FHIR instance might (will) carry additional information that is not part of the zib. If a system implements a zib, all information can be communicated in FHIR. If it implements more than the zib (by allowing text formatting for example), this is a nice feature but there's no requirement that the receiving system will be able to interpret it.

**Comment by ArdonToonstra** [comment]
Some comments from my colleagues: _"In theory, the author of the text in the ST never intended the text to be rendered as Markdown, so you are adding interpretation.  In practice, I think the alternatives (not mapping the field) are worse."_ and _"and of course the point of markdown is that it's both "just a text" and parsable for markup."_

Together with your first thoughts, I guess we can move towards agreeing we can map ST to MarkDown.

**Comment by pieter-edelman-nictiz** [comment]
I've added it on Vprepub to the data type mapping table and to the zib compliance tool.
