### ISSUE TITLE
ServiceRequest.requester 0..1 versus zib requester 0..*

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#69]
In our current modelling, we have mapped the zib Procedure concept 'Requester::HealthProfessional' on ServiceRequest.requester. However, the cardinality does not match.

**Comment by pieter-edelman-nictiz** [comment]
In addition, `Procedure.extension:procedureMethod` has a cardinality of 0..1, which doesn't match with ProcedureMethod from the zib, which has a cardinality of 0..*.

**Comment by ahenket** [comment]
The CIM has 0..* for requester and then says "**The healthcare provider** who requested the procedure."

In the HL7 Validation Team we were unable to come up with a situation where more than 1 requester is applicable. Suggest to file a CIM-ticket for this and ask if 0..* is a typo

**Comment by pieter-edelman-nictiz** [comment]
Zib issue created: https://bits.nictiz.nl/browse/ZIB-1488

**Comment by pieter-edelman-nictiz** [comment]
Since there's a preliminary answer and so far, there seems to be agreement that the cardinality of the zib is too wide, this issue can be closed.
