### ISSUE TITLE
zib-Encounter Location 0..1 versus FHIR Encounter.location 0..*

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#74]
According to our profiling guidelines, we should restrict the `Encounter.location` element to 0..1 because this element is mapped to the zib Location::HealthcareProvider concept (https://zibs.nl/wiki/Encounter-v4.0.1(2020EN)).

However, this will lose functionality that FHIR has modelled: it is possible to capture a whole path of locations (with status and time indications) of where the encounter took place. Probably, the zibs doesn't recognize this fine granularity of locations or thinks of using multiple zib Encounter instances.  (Which don't have a concept that can relate them like `Encounter.partOf`)

**Comment by ArdonToonstra** [comment]
Related BITS ticket: https://bits.nictiz.nl/browse/ZIB-1414 
TODO: will create a new zib ticket to pose this problem. For now leave `Encounter.location` as is.

**Comment by ArdonToonstra** [comment]
https://bits.nictiz.nl/browse/ZIB-1632

**Comment by pieter-edelman-nictiz** [comment]
Conclusie zib-centrum: kardinaliteit mag wel groter zijn.

**Comment by pieter-edelman-nictiz** [comment]
This change has been implemented
