### ISSUE TITLE
Mapping of zib Procedure to Procedure/ServiceRequest

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#80]
The zib Procedure describes past, present and future procedures. The `Procedure` resource describes only past and present procedures. The resource is pretty clear about that. The `ServiceRequest` resource describes future procedures that are proposed/planned/ordered etc. 

Our current approach is to map the zib to both resources and provide a clear description of when to use which resource (based on StartDateTime). The zib requester information will only be mapped to the native `ServiceRequest.requester` element. 

However, it has been made clear by the zibs centre that the zib is not an actual 'request' and does not contain any logistic or process information. Based on the resource name it may seem that this, therefore, is not a correct mapping. 

Options:
* map to both `Procedure` and `ServiceRequest` with documentation
* don't map the future procedures of the zib Procedure. Potentially include this at the nl-core- level as it may be likely that there will be implementations using `ServiceRequest`.

**Comment by ahenket** [comment]
To create a ServiceRequest you need at least .status, .intent and .subject.

For .status you could default 'unknown' is you have nothing else. For .intent you could use 'order' if you have a Procedure, but that is interpretation. .subject is likely no problem (Patient).

It does introduce a lot of hassle to 'just' get to Requester, but I don't think there is a different way in FHIR. The zibs would be better served with a little more notion of status/workflow.

**Comment by ArdonToonstra** [comment]
A solution has been created in a different issue which has been documented here: https://informatiestandaarden.nictiz.nl/wiki/FHIR:V1.0_FHIR_Profiling_Guidelines_R4#Canonical_URL.2C_id.2C_name_and_title
