### ISSUE TITLE
Should Quantity.system be fixed to http://unitsofmeasure.org ?

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#85]
The zibs [describe](https://zibs.nl/wiki/Legend) the _PQ_ datatype as follows:

> Datatype PQ: physical quantity. Data element that expresses a quantity and a unit of measure, typically the result of a measurement. The units of measure are to be selected from the UCUM system. 

It's not always explicitly mentioned what the unit should be for an element of type _PQ_, but it should be UCUM. Therefore, it may be a good idea to at least fix the value of `Quantity.system` to "http://unitsofmeasure.org/" (when it represents a _PQ_). This would provide guidance to the implementer that UCUM should be used.

**Comment by Ashwin-nictiz** [comment]
I think it would be a good idea to clarify this for the implementer.

**Comment by ArdonToonstra** [comment]
It's also a SHOULD from the FHIR spec. "If the unit can be coded in UCUM and a code is provided, it SHOULD be a UCUM code." - http://hl7.org/fhir/datatypes.html#Quantity 

However, I would rather not fix `Quantity.system` as this limits potential reuse and goes into the open world modeling? Moreover, I think the zib is wrong here by stating this that hard. The quantities in MP are based on the G-standard AND also in many MP zibs a scentense like this is included: "Optionally a translation to NHG table Gebruiksvoorschriften(Table 25) is also allowed."  https://zibs.nl/wiki/MedicationAdministration2-v1.1.1(2020EN)

**Comment by pieter-edelman-nictiz** [comment]
Ok, sounds reasonable. I'm closing this issue.
