### ISSUE TITLE
Mandatory FHIR elements (1..1) with zib cardinality 0..1

### ISSUE THREAD

**Issue by jd-nictiz** [Nictiz/Nictiz-R4-zib2020#97]
Related to #45, but not quite. #45 covers the case where a FHIR element with no zib mapping has cardinality 1..1. I would like to point out two other situations:

1. FHIR element with zib mapping has cardinality 1..1, where the zib cardinality is 0..1.
2. FHIR element with zib mapping has cardinality 1..1, where the zib cardinality is also 1..1, but 0..1 is expected because of conceptual cardinality.

Examples of this are TextResult::TextResultStatus on DiagnosticReport.status (case 2) and the to-be-mapped TreatmentObjective::DesiredHealthcareResult on Goal.description (case 1).

Plus, there is also the case that a code/CodeableConcept with a required binding cannot be escaped with a nullFlavor/data-absent-reason (which is applicable to the TextResultStatus example), which leads to a matrix of situations that should be covered.

I think we should add guidance to the Profiling Guidelines (and in the future the IG) about what is expected in these cases.

|                                                                                                                                                     | Required binding on FHIR element                                                                                      | No required binding on FHIR element                                                                                   |
|-----------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| FHIR element witout zib mapping has cardinality 1..1                                                                                                | #45                                                                                                                   | #45?                                                                                                                  |
| FHIR element with zib mapping has cardinality 1..1, where the zib cardinality is 0..1                                                               | Guidance on FHIR element on what to do when zib instance does not have element?                                       | NullFlavor or DAR-extension described in IG? Example: TreatmentObjective::DesiredHealthcareResult on Goal.description |
| FHIR element with zib mapping has cardinality 1..1, where the zib cardinality is also 1..1, but 0..1 is expected because of conceptual cardinality. | Guidance on FHIR element on what to do when zib instance does not have element? Example: TextResult::TextResultstatus | NullFlavor or DAR-extension described in IG?                                                                          |

**Comment by jduwel** [comment]
Can't find if nullFlavor/DAR extension is allowed on Example/Preferred binding or if they expect you to create a valueset with includes some UNK code.

**Comment by pieter-edelman-nictiz** [comment]
My 2c: the stance of FHIR is that if something is required, it is required. So if there's a required binding on a required element, there just seems to be no escape: systems will have to capture this information, not because of the zib or the data set, but because of the use of FHIR. In my experience, the elements that are required by FHIR are unrealistic to leave out from a zib instance as well.

If there's no required binding, an implementer can provide a NullFlavor code. I think it's enough to specify this on the IG level; the intent is after all that this is an escape, not a "first-class" solution.

**Comment by jduwel** [comment]
Proposal for wiki text:
https://informatiestandaarden.nictiz.nl/wiki/FHIR:Vissue-github-97_FHIR_Profiling_Guidelines_R4#Mandatory_FHIR_elements

**Comment by ArdonToonstra** [comment]
@jduwel , I have rephrased a couple of sentences. Please have a look and adjust it if you want.

**Comment by pieter-edelman-nictiz** [comment]
I don't fully agree to provide guidance here for implementers; that's something that should be left to an implementation guide. Especially in this situation it wouldn't be unthinkable that the information standard makes a concept required, thus negating the idea that it could be handed with data-absent-reason. I tweaked the text proposal to this end.

**Comment by pieter-edelman-nictiz** [comment]
Integrated
